name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Format
        run: npm run format:ci
      - name: Lint
        run: npm run lint
      - name: Unit test
        run: npm run test
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: End-to-end test
        run: npm run test:e2e
        env:
          REACT_APP_CLIENT_ID: "value-not-used-by-fake"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots/
            cypress/videos/
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build container
        run: docker build .
